import React, { useEffect, useMemo, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Search, ShoppingCart, ChevronRight, Home, Settings2, Grid2X2, MessageCircle, Instagram, Facebook, ArrowLeft, Plus, Save, Star, Minus, Trash2, X, Package, SlidersHorizontal, ImagePlus } from 'lucide-react'
import './index.css'
import './cart.css'

type Product = {
  name: string
  price: string
  old: string
  image: string
  images: string[]
  category: string
  subcategory: string
  colors: string[]
  sizes: string[]
  description: string
  material: string
  gender: string
  fit: string
  sku: string
  stock: string
  brand: string
  tags: string[]
}
type SocialLinks = { whatsapp: string; instagram: string; facebook: string }
type CartItem = Product & { quantity: number }
type AdminSection = 'menu' | 'social' | 'vitrine' | 'add' | 'products'

const categories = ['Feminino','Masculino','Unissex','Vestidos','Blusas e Camisetas','Calças','Shorts e Bermudas','Saias','Conjuntos','Moda Íntima','Fitness','Casacos e Jaquetas','Calçados','Bolsas','Acessórios']
const colorOptions = ['Preto','Branco','Cinza','Bege','Marrom','Vermelho','Laranja','Amarelo','Verde','Azul','Rosa','Roxo']
const sizeOptions = ['PP','P','M','G','GG','XG','36','38','40','42','44','46']

const makeProduct = (data: Partial<Product> & Pick<Product, 'name'|'price'|'old'|'image'>): Product => ({
  name: data.name, price: data.price, old: data.old, image: data.image,
  images: data.images?.length ? data.images : [data.image],
  category: data.category || 'Unissex', subcategory: data.subcategory || '', colors: data.colors || [], sizes: data.sizes || [],
  description: data.description || '', material: data.material || '', gender: data.gender || 'Unissex', fit: data.fit || 'Regular',
  sku: data.sku || '', stock: data.stock || '', brand: data.brand || 'Urban Fit', tags: data.tags || []
})

const initialProducts: Product[] = [
  makeProduct({ name:'Moletom Oversized', price:'R$ 179', old:'R$ 219', image:'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=700&q=85', category:'Masculino', subcategory:'Moletons', colors:['Preto','Bege'], sizes:['P','M','G','GG'], fit:'Oversized', material:'Algodão', description:'Moletom confortável para o dia a dia, com visual urbano.' }),
  makeProduct({ name:'Calça Cargo', price:'R$ 199', old:'R$ 249', image:'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=700&q=85', category:'Masculino', subcategory:'Calças', colors:['Preto','Bege'], sizes:['38','40','42','44'], fit:'Cargo', material:'Sarja' }),
  makeProduct({ name:'Tênis Esportivo', price:'R$ 289', old:'R$ 359', image:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=85', category:'Calçados', subcategory:'Tênis', colors:['Vermelho','Branco','Preto'], sizes:['38','40','42','44'], material:'Sintético' }),
  makeProduct({ name:'Camiseta Básica', price:'R$ 69', old:'R$ 89', image:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=700&q=85', category:'Blusas e Camisetas', colors:['Branco','Preto','Cinza'], sizes:['P','M','G','GG'], material:'Algodão' }),
  makeProduct({ name:'Polo Premium', price:'R$ 89', old:'R$ 119', image:'https://images.unsplash.com/photo-1586363104868-3a5e2ab60d99?auto=format&fit=crop&w=700&q=85', category:'Masculino', subcategory:'Polo', colors:['Branco','Azul','Preto'], sizes:['P','M','G','GG'], material:'Algodão' }),
  makeProduct({ name:'Boné RS', price:'R$ 59', old:'R$ 79', image:'https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=700&q=85', category:'Acessórios', colors:['Preto','Bege'], sizes:['Único'], material:'Algodão' }),
  makeProduct({ name:'Jaqueta Corta-Vento', price:'R$ 289', old:'R$ 359', image:'https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?auto=format&fit=crop&w=700&q=85', category:'Casacos e Jaquetas', colors:['Preto','Verde'], sizes:['P','M','G','GG'], material:'Poliéster' }),
  makeProduct({ name:'Moletom Básico', price:'R$ 179', old:'R$ 229', image:'https://images.unsplash.com/photo-1578681994506-b8f463449011?auto=format&fit=crop&w=700&q=85', category:'Unissex', colors:['Cinza','Preto'], sizes:['P','M','G','GG'], material:'Algodão' }),
  makeProduct({ name:'Tênis Casual', price:'R$ 249', old:'R$ 309', image:'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=700&q=85', category:'Calçados', subcategory:'Tênis', colors:['Branco','Preto'], sizes:['38','40','42','44'], material:'Sintético' }),
  makeProduct({ name:'Bermuda Cargo', price:'R$ 149', old:'R$ 189', image:'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&w=700&q=85', category:'Shorts e Bermudas', colors:['Bege','Preto'], sizes:['38','40','42','44'], material:'Sarja' }),
  makeProduct({ name:'Shoulder Bag', price:'R$ 99', old:'R$ 129', image:'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=700&q=85', category:'Bolsas', colors:['Preto','Marrom'], sizes:['Único'], material:'Nylon' }),
  makeProduct({ name:'Legging Esportiva', price:'R$ 119', old:'R$ 149', image:'https://images.unsplash.com/photo-1506629905607-d9e0a1d0f2b8?auto=format&fit=crop&w=700&q=85', category:'Fitness', gender:'Feminino', colors:['Preto','Rosa'], sizes:['P','M','G'], material:'Poliamida' })
]

const heroImage = 'https://cdn.myikas.com/images/8ef8ae14-2b23-422b-b06b-a7afcbd0683a/6adbcf63-691a-4e8b-a9a9-2c0ef1255cdf/3840/du9a0452.webp'
const defaultSocials: SocialLinks = { whatsapp:'https://wa.me/5511987654321', instagram:'https://instagram.com/urbanfit.oficial', facebook:'https://facebook.com/urbanfit.oficial' }
const priceValue = (price: string) => { const text=String(price||'').replace(/[^\d,.]/g,''); if(text.includes(',')) return Number(text.replace(/\./g,'').replace(',','.'))||0; return Number(text)||0 }
const formatPrice = (value: string) => { const n=priceValue(value); return n>0 ? `R$ ${n.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})}` : '' }
const normalizeProduct = (p: any): Product => makeProduct({ ...p, image:p.image || p.images?.[0] || '' })

function App() {
  const [tab,setTab]=useState<'home'|'search'|'admin'>('home')
  const [query,setQuery]=useState('')
  const [products,setProducts]=useState<Product[]>(()=>{ try { const saved=JSON.parse(localStorage.getItem('urbanfit-products')||'null'); return Array.isArray(saved)&&saved.length ? saved.map(normalizeProduct) : initialProducts } catch { return initialProducts } })
  const [cartItems,setCartItems]=useState<CartItem[]>(()=>{ try{return JSON.parse(localStorage.getItem('urbanfit-cart')||'[]')||[]}catch{return[]} })
  const [cartOpen,setCartOpen]=useState(false)
  const [selected,setSelected]=useState<Product|null>(null)
  const [vitrineOpen,setVitrineOpen]=useState(false)
  const [socials,setSocials]=useState<SocialLinks>(()=>{try{return JSON.parse(localStorage.getItem('urbanfit-socials')||'')||defaultSocials}catch{return defaultSocials}})
  const [featured,setFeatured]=useState<string[]>(()=>{try{const s=JSON.parse(localStorage.getItem('urbanfit-featured')||'null');return Array.isArray(s)?s:initialProducts.slice(0,4).map(p=>p.name)}catch{return initialProducts.slice(0,4).map(p=>p.name)}})
  const heroRef=useRef<HTMLImageElement>(null)
  const filtered=useMemo(()=>products.filter(p=>`${p.name} ${p.category} ${p.subcategory} ${p.colors.join(' ')}`.toLowerCase().includes(query.toLowerCase())),[products,query])
  const featuredProducts=useMemo(()=>products.filter(p=>featured.includes(p.name)),[products,featured])
  const cartCount=cartItems.reduce((s,i)=>s+i.quantity,0)
  const cartTotal=cartItems.reduce((s,i)=>s+priceValue(i.price)*i.quantity,0)
  const addToCart=(product:Product)=>setCartItems(current=>{const found=current.find(i=>i.name===product.name);return found?current.map(i=>i.name===product.name?{...i,quantity:i.quantity+1}:i):[...current,{...product,quantity:1}]})
  const changeQuantity=(name:string,delta:number)=>setCartItems(c=>c.map(i=>i.name===name?{...i,quantity:i.quantity+delta}:i).filter(i=>i.quantity>0))
  const removeFromCart=(name:string)=>setCartItems(c=>c.filter(i=>i.name!==name))
  useEffect(()=>{localStorage.setItem('urbanfit-products',JSON.stringify(products))},[products])
  useEffect(()=>{localStorage.setItem('urbanfit-cart',JSON.stringify(cartItems))},[cartItems])
  useEffect(()=>{localStorage.setItem('urbanfit-socials',JSON.stringify(socials))},[socials])
  useEffect(()=>{localStorage.setItem('urbanfit-featured',JSON.stringify(featured))},[featured])
  useEffect(()=>{if(heroRef.current)heroRef.current.animate([{opacity:0,transform:'translateY(18px) scale(.98)'},{opacity:1,transform:'translateY(0) scale(1)'}],{duration:650,easing:'cubic-bezier(.22,1,.36,1)',fill:'both'})},[])
  if(selected)return <ProductView product={selected} onBack={()=>setSelected(null)} onAdd={()=>addToCart(selected)} whatsapp={socials.whatsapp}/>
  return <div className="app-shell"><div className="phone-content"><header className="topbar"><button className="menu-button" aria-label="menu"><span></span><span></span><span></span></button><div className="brand"><span className="brand-mark"><i></i></span><strong>URBAN FIT</strong></div></header>
    {cartOpen?<CartPage items={cartItems} total={cartTotal} onBack={()=>setCartOpen(false)} onIncrement={n=>changeQuantity(n,1)} onDecrement={n=>changeQuantity(n,-1)} onRemove={removeFromCart}/>:tab==='search'?<SearchPage query={query} setQuery={setQuery} products={filtered} onSelect={setSelected}/>:tab==='admin'?<AdminPage products={products} setProducts={setProducts} socials={socials} setSocials={setSocials} featured={featured} setFeatured={setFeatured}/>:vitrineOpen?<VitrinePage products={featuredProducts} onBack={()=>setVitrineOpen(false)} onSelect={setSelected}/>:<main>
      <section className="feature-grid"><div className="orange-backdrop"></div><div className="hero-image"><img ref={heroRef} src={heroImage} alt="Modelo Urban Fit"/></div><div className="hero-copy"><div className="hero-title">ROUPAS E<br/>CALÇADOS<br/>PARA O<br/>DIA A DIA</div></div>
        <section className="contact-card"><h2>Fale com a gente</h2><p>Estamos sempre por perto!</p><Contact icon={<MessageCircle/>} title="WhatsApp" detail="Falar no WhatsApp" href={socials.whatsapp}/><Contact icon={<Instagram/>} title="Instagram" detail="@urbanfit.oficial" href={socials.instagram}/><Contact icon={<Facebook/>} title="Facebook" detail="/urbanfit.oficial" href={socials.facebook}/></section>
        <button className="vitrine" onClick={()=>setVitrineOpen(true)}><Grid2X2 size={20}/> Vitrine</button></section>
      <section id="products" className="product-section"><div className="section-head"><h2>Produtos</h2><button onClick={()=>setTab('search')}>Ver Todos <ChevronRight size={18}/></button></div><div className="product-grid">{products.map(p=><ProductCard key={p.name} product={p} onSelect={setSelected}/>)}</div></section>
    </main>}</div>
    <nav className="bottom-nav"><button className={tab==='home'&&!cartOpen?'active':''} onClick={()=>{setTab('home');setCartOpen(false);setVitrineOpen(false)}}><Home/><span>Início</span></button><button className={tab==='search'&&!cartOpen?'active':''} onClick={()=>{setTab('search');setCartOpen(false);setVitrineOpen(false)}}><Search/><span>Busca</span></button><button className={cartOpen?'active':''} onClick={()=>{setCartOpen(true);setVitrineOpen(false)}}><ShoppingCart/><span>Carrinho</span>{cartCount>0&&<b className="cart-nav-badge">{cartCount}</b>}</button><button className={tab==='admin'&&!cartOpen?'active':''} onClick={()=>{setTab('admin');setCartOpen(false);setVitrineOpen(false)}}><Settings2/><span>Painel ADM</span></button></nav>
  </div>
}

function Contact({icon,title,detail,href}:{icon:React.ReactNode;title:string;detail:string;href:string}){return <a className="contact-row" href={href||'#'} target="_blank" rel="noopener noreferrer"><span className="contact-icon">{icon}</span><div><strong>{title}</strong><small>{detail}</small></div><ChevronRight size={17}/></a>}
function ProductCard({product,onSelect}:{product:Product;onSelect:(p:Product)=>void}){return <button className="product-card" onClick={()=>onSelect(product)}><div className="product-photo"><img src={product.image} loading="lazy" alt={product.name}/></div><div className="product-name">{product.name}</div><div className="prices"><b>{product.price}</b><del>{product.old}</del></div></button>}
function SearchPage({query,setQuery,products,onSelect}:{query:string;setQuery:(s:string)=>void;products:Product[];onSelect:(p:Product)=>void}){const [category,setCategory]=useState('Todas');const list=category==='Todas'?products:products.filter(p=>p.category===category);return <main className="search-page"><div className="search-box"><Search/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar roupa, calçado, cor..."/></div><div className="category-scroll"><button className={category==='Todas'?'active':''} onClick={()=>setCategory('Todas')}>Todas</button>{categories.map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><h1>Resultados</h1><div className="product-grid">{list.length?list.map(p=><ProductCard key={p.name} product={p} onSelect={onSelect}/>):<div className="empty-vitrine">Nenhum produto encontrado.</div>}</div></main>}
function VitrinePage({products,onBack,onSelect}:{products:Product[];onBack:()=>void;onSelect:(p:Product)=>void}){return <main className="vitrine-page"><button className="back" onClick={onBack}><ArrowLeft/> Voltar</button><div className="vitrine-page-head"><div><span className="detail-label">URBAN FIT</span><h1>Vitrine</h1><p>As melhores peças selecionadas para você.</p></div><Star className="vitrine-page-star"/></div>{products.length?<div className="product-grid">{products.map(p=><ProductCard key={p.name} product={p} onSelect={onSelect}/>)}</div>:<div className="vitrine-empty"><Star/><h2>Vitrine vazia</h2><p>Escolha os produtos no Painel ADM → Vitrine.</p></div>}</main>}
function CartPage({items,total,onBack,onIncrement,onDecrement,onRemove}:{items:CartItem[];total:number;onBack:()=>void;onIncrement:(name:string)=>void;onDecrement:(name:string)=>void;onRemove:(name:string)=>void}){return <main className="cart-page"><button className="back cart-back" onClick={onBack}><ArrowLeft/> Voltar</button>{items.length?<><div className="cart-head"><div><span className="detail-label">URBAN FIT</span><h1>Seu carrinho</h1><p>Guarde produtos e veja o valor de todos juntos.</p></div><div className="cart-icon-wrap"><ShoppingCart/><b className="cart-count">{items.reduce((s,i)=>s+i.quantity,0)}</b></div></div><div className="cart-list">{items.map(item=><article className="cart-item" key={item.name}><div className="cart-item-photo"><img src={item.image} alt={item.name}/></div><div className="cart-item-info"><strong>{item.name}</strong><span className="cart-item-price">{item.price}</span><div className="cart-controls"><button aria-label="diminuir" onClick={()=>onDecrement(item.name)}><Minus size={15}/></button><span>{item.quantity}</span><button aria-label="aumentar" onClick={()=>onIncrement(item.name)}><Plus size={15}/></button></div></div><button className="cart-remove" onClick={()=>onRemove(item.name)} aria-label={`Remover ${item.name}`}><Trash2 size={17}/></button></article>)}</div><div className="cart-summary"><div className="cart-summary-row"><span>Total da seleção</span><strong>R$ {total.toFixed(2).replace('.',',')}</strong></div><small className="cart-note">Este carrinho serve apenas para organizar os produtos e consultar o valor total. Não há finalização de compra.</small></div></>:<div className="cart-empty"><ShoppingCart/><h2>Seu carrinho está vazio</h2><p>Abra uma roupa e toque em “Guardar no carrinho”.</p></div>}</main>}

function ProductView({product,onBack,onAdd,whatsapp}:{product:Product;onBack:()=>void;onAdd:()=>void;whatsapp:string}){const [photo,setPhoto]=useState(0);const photos=product.images?.length?product.images:[product.image];return <main className="detail"><button className="back" onClick={onBack}><ArrowLeft/> Voltar</button><div className="detail-gallery"><div className="detail-photo"><img src={photos[photo]||product.image} alt={product.name}/></div>{photos.length>1&&<div className="detail-thumbs">{photos.map((img,i)=><button key={`${img}-${i}`} className={i===photo?'active':''} onClick={()=>setPhoto(i)}><img src={img} alt=""/></button>)}</div>}</div><div className="detail-label">{product.category}{product.subcategory?` · ${product.subcategory}`:''}</div><h1>{product.name}</h1><div className="detail-price">{product.price}{product.old&&<del>{product.old}</del>}</div>{product.colors.length>0&&<div className="detail-meta"><strong>Cores</strong><div className="meta-pills">{product.colors.map(c=><span key={c}>{c}</span>)}</div></div>}{product.sizes.length>0&&<div className="detail-meta"><strong>Tamanhos</strong><div className="meta-pills">{product.sizes.map(s=><span key={s}>{s}</span>)}</div></div>}<p className="detail-text">{product.description||'Peça selecionada da Urban Fit.'}</p><div className="detail-info-grid">{product.material&&<div><small>Material</small><b>{product.material}</b></div>}{product.fit&&<div><small>Modelagem</small><b>{product.fit}</b></div>}{product.brand&&<div><small>Marca</small><b>{product.brand}</b></div>}{product.sku&&<div><small>SKU</small><b>{product.sku}</b></div>}</div><button className="buy" onClick={onAdd}><ShoppingCart size={18}/> Guardar no carrinho</button><a className="whatsapp-detail" href={whatsapp||'#'} target="_blank" rel="noopener noreferrer"><MessageCircle size={17}/> Perguntar pelo WhatsApp</a></main>}

const resizeImageFile = (file:File):Promise<string> => new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const max=1400;const scale=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext('2d');if(!ctx){reject(new Error('canvas'));return}ctx.drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.82))};img.onerror=()=>reject(new Error('image'));img.src=String(reader.result)};reader.onerror=()=>reject(new Error('file'));reader.readAsDataURL(file)})

function AdminPage({products,setProducts,socials,setSocials,featured,setFeatured}:{products:Product[];setProducts:React.Dispatch<React.SetStateAction<Product[]>>;socials:SocialLinks;setSocials:React.Dispatch<React.SetStateAction<SocialLinks>>;featured:string[];setFeatured:React.Dispatch<React.SetStateAction<string[]>>}){
  const [section,setSection]=useState<AdminSection>('menu')
  const [socialOpen,setSocialOpen]=useState(false)
  const [vitrineOpen,setVitrineOpen]=useState(false)
  const [draft,setDraft]=useState(socials)
  const [featuredDraft,setFeaturedDraft]=useState(featured)
  const emptyForm={name:'',price:'',old:'',category:'Feminino',subcategory:'',gender:'Feminino',colors:[] as string[],sizes:[] as string[],description:'',material:'',fit:'Regular',sku:'',stock:'',brand:'Urban Fit',tags:'',images:[] as string[]}
  const [form,setForm]=useState(emptyForm)
  const [error,setError]=useState('')
  const [photoError,setPhotoError]=useState('')
  const [readingPhotos,setReadingPhotos]=useState(false)
  useEffect(()=>{setDraft(socials)},[socials])
  useEffect(()=>{setFeaturedDraft(featured)},[featured])
  const saveSocial=()=>{setSocials(draft);setSocialOpen(false)}
  const saveVitrine=()=>{setFeatured(featuredDraft);setVitrineOpen(false)}
  const toggle=(key:'colors'|'sizes',value:string)=>setForm(f=>({...f,[key]:f[key].includes(value)?f[key].filter(x=>x!==value):[...f[key],value]}))
  const removePhoto=(index:number)=>setForm(f=>({...f,images:f.images.filter((_,i)=>i!==index)}))
  const handlePhotos=async(e:React.ChangeEvent<HTMLInputElement>)=>{const files=Array.from(e.target.files||[]);e.target.value='';if(!files.length)return;const available=10-form.images.length;if(available<=0){setPhotoError('Você já atingiu o limite de 10 fotos.');return}const chosen=files.slice(0,available);setReadingPhotos(true);setPhotoError('');try{const converted=await Promise.all(chosen.map(resizeImageFile));setForm(f=>({...f,images:[...f.images,...converted].slice(0,10)}));if(files.length>available)setPhotoError('O limite é de 10 fotos. As primeiras foram adicionadas.')}catch{setPhotoError('Não foi possível carregar uma das fotos. Tente novamente.')}finally{setReadingPhotos(false)}}
  const resetForm=()=>{setForm(emptyForm);setError('');setPhotoError('');setReadingPhotos(false)}
  const addProduct=()=>{
    const cleanImages=form.images.filter(Boolean)
    if(!form.name.trim()||!form.price.trim()){setError('Preencha pelo menos o nome e o preço.');return}
    if(cleanImages.length<3||cleanImages.length>10){setPhotoError('Selecione no mínimo 3 e no máximo 10 fotos da galeria.');return}
    if(products.some(p=>p.name.toLowerCase()===form.name.trim().toLowerCase())){setError('Já existe uma roupa com esse nome.');return}
    const product=makeProduct({name:form.name.trim(),price:formatPrice(form.price.trim())||form.price.trim(),old:formatPrice(form.old.trim()),image:cleanImages[0],images:cleanImages,category:form.category,subcategory:form.subcategory.trim(),gender:form.gender,colors:form.colors,sizes:form.sizes,description:form.description.trim(),material:form.material.trim(),fit:form.fit.trim()||'Regular',sku:form.sku.trim(),stock:form.stock.trim(),brand:form.brand.trim()||'Urban Fit',tags:form.tags.split(',').map(s=>s.trim()).filter(Boolean)})
    setProducts(current=>[product,...current]);setFeatured(current=>current.includes(product.name)?current:[...current,product.name]);resetForm();setSection('products')
  }
  const removeProduct=(name:string)=>{if(window.confirm(`Remover “${name}” do catálogo?`)){setProducts(c=>c.filter(p=>p.name!==name));setFeatured(c=>c.filter(n=>n!==name))}}
  const openSection=(next:AdminSection)=>{setSection(next);setSocialOpen(false);setVitrineOpen(false);setError('');setPhotoError('')}
  return <main className="admin-page"><div className="admin-head"><div><span className="detail-label">URBAN FIT</span><h1>Painel ADM</h1><p>Controle completo do catálogo da loja.</p></div></div>
    {section==='menu'&&<><div className="admin-stats"><div><Package/><strong>{products.length}</strong><span>Produtos</span></div><div><Star/><strong>{featured.length}</strong><span>Na vitrine</span></div><div><SlidersHorizontal/><strong>{categories.length}</strong><span>Categorias</span></div></div><div className="admin-action-grid"><button className="admin-social-button" onClick={()=>openSection('products')}><Package/><strong>Produtos</strong><span>Ver e excluir itens do catálogo</span></button><button className="admin-social-button" onClick={()=>openSection('social')}><MessageCircle/><strong>Redes sociais</strong><span>Editar os links de contato</span></button><button className="admin-social-button" onClick={()=>openSection('vitrine')}><Star/><strong>Vitrine</strong><span>Escolher quais produtos aparecem nela</span></button><button className="admin-social-button admin-action-main" onClick={()=>openSection('add')}><Plus/><strong>Adicionar</strong><span>Cadastrar roupa, detalhes, cores, tamanhos e fotos</span></button></div><div className="admin-guide"><strong>Como usar</strong><span>Cada botão acima abre uma área diferente. Nada fica misturado.</span></div></>}
    {section!=='menu'&&<button className="admin-section-back" onClick={()=>openSection('menu')}><ArrowLeft size={17}/> Voltar ao painel</button>}
    {section==='social'&&<section className="admin-panel-card"><div className="social-settings-head"><div><h2>Redes sociais</h2><p>Esses links aparecem no contato da página inicial.</p></div><button className="social-save" onClick={saveSocial}><Save size={15}/> Salvar</button></div><label>WhatsApp<input value={draft.whatsapp} onChange={e=>setDraft({...draft,whatsapp:e.target.value})}/></label><label>Instagram<input value={draft.instagram} onChange={e=>setDraft({...draft,instagram:e.target.value})}/></label><label>Facebook<input value={draft.facebook} onChange={e=>setDraft({...draft,facebook:e.target.value})}/></label><small className="social-help">Use os links completos, começando por https://</small></section>}
    {section==='vitrine'&&<section className="admin-panel-card"><div className="social-settings-head"><div><h2>Vitrine</h2><p>Marque os produtos que deseja destacar.</p></div><button className="social-save" onClick={saveVitrine}><Save size={15}/> Salvar</button></div><div className="featured-list">{products.map(p=><label className="featured-option" key={p.name}><input type="checkbox" checked={featuredDraft.includes(p.name)} onChange={()=>setFeaturedDraft(c=>c.includes(p.name)?c.filter(n=>n!==p.name):[...c,p.name])}/><img src={p.image} alt=""/><span><strong>{p.name}</strong><small>{p.category} · {p.price}</small></span></label>)}</div></section>}
    {section==='products'&&<section className="admin-list"><h2>Produtos cadastrados</h2>{products.map(p=><div className="admin-item" key={p.name}><img src={p.image} alt=""/><div><strong>{p.name}</strong><small>{p.category} · {p.price}</small><em>{p.images.length} fotos · {p.colors.length} cores · {p.sizes.length} tamanhos</em></div><button onClick={()=>removeProduct(p.name)} aria-label={`Excluir ${p.name}`}><Trash2 size={15}/></button></div>)}</section>}
    {section==='add'&&<section className="add-product-panel"><div className="add-product-title"><div><span className="detail-label">NOVO CADASTRO</span><h2>Adicionar roupa</h2><p>Preencha os dados para deixar o produto pronto para a vitrine.</p></div><button className="admin-close" onClick={()=>openSection('menu')}><X/></button></div>
      <div className="form-section"><h3>1. Informações principais</h3><div className="form-grid"><label>Nome da roupa *<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex.: Vestido Midi Elegance"/></label><label>Categoria *<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Subcategoria<input value={form.subcategory} onChange={e=>setForm({...form,subcategory:e.target.value})} placeholder="Ex.: Vestidos midi"/></label><label>Gênero<select value={form.gender} onChange={e=>setForm({...form,gender:e.target.value})}><option>Feminino</option><option>Masculino</option><option>Unissex</option></select></label><label>Preço de venda *<input inputMode="decimal" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} placeholder="R$ 149,90"/></label><label>Preço antigo<input inputMode="decimal" value={form.old} onChange={e=>setForm({...form,old:e.target.value})} placeholder="R$ 199,90"/></label><label>SKU / referência<input value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})} placeholder="UF-001"/></label><label>Estoque / disponibilidade<input value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})} placeholder="Ex.: 25 unidades"/></label><label>Marca<input value={form.brand} onChange={e=>setForm({...form,brand:e.target.value})} placeholder="Urban Fit"/></label><label>Modelagem<input value={form.fit} onChange={e=>setForm({...form,fit:e.target.value})} placeholder="Regular, slim, oversized..."/></label></div></div>
      <div className="form-section"><h3>2. Cores disponíveis</h3><p className="form-help">Selecione todas as cores dessa roupa.</p><div className="choice-grid">{colorOptions.map(c=><button type="button" key={c} className={form.colors.includes(c)?'choice active':'choice'} onClick={()=>toggle('colors',c)}>{c}</button>)}</div></div>
      <div className="form-section"><h3>3. Tamanhos</h3><p className="form-help">Selecione os tamanhos vendidos.</p><div className="choice-grid size-grid">{sizeOptions.map(s=><button type="button" key={s} className={form.sizes.includes(s)?'choice active':'choice'} onClick={()=>toggle('sizes',s)}>{s}</button>)}</div></div>
      <div className="form-section"><h3>4. Fotos do produto</h3><p className="form-help"><b>Obrigatório: 3 fotos.</b> Selecione diretamente da galeria do celular. Você pode colocar até 10.</p><label className="gallery-upload"><ImagePlus size={20}/><span>{readingPhotos?'Carregando fotos...':`Selecionar fotos da galeria (${form.images.length}/10)`}</span><input type="file" accept="image/*" multiple disabled={readingPhotos||form.images.length>=10} onChange={handlePhotos}/></label><div className="photo-preview-grid">{form.images.map((img,i)=><div className="photo-preview" key={`${img}-${i}`}><img src={img} alt={`Foto ${i+1}`}/><span>{i===0?'Principal':`Foto ${i+1}`}</span><button type="button" onClick={()=>removePhoto(i)} aria-label={`Remover foto ${i+1}`}><X size={14}/></button></div>)}</div>{form.images.length>0&&<p className="form-help photo-count">{form.images.length<3?`Faltam ${3-form.images.length} foto(s) para cadastrar.`:`${form.images.length} foto(s) selecionada(s).`}</p>}{photoError&&<p className="form-error">{photoError}</p>}</div>
      <div className="form-section"><h3>5. Descrição e detalhes</h3><div className="form-grid"><label className="full-field">Descrição completa<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Descreva o tecido, acabamento, ocasião de uso, caimento e diferenciais..."/></label><label>Material / composição<input value={form.material} onChange={e=>setForm({...form,material:e.target.value})} placeholder="Ex.: 95% algodão, 5% elastano"/></label><label>Tags / palavras-chave<input value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})} placeholder="streetwear, casual, verão"/></label></div></div>
      {error&&<p className="form-error">{error}</p>}<div className="add-product-actions"><button className="secondary-admin-button" onClick={resetForm}>Limpar</button><button className="admin-add save-product-button" onClick={addProduct} disabled={readingPhotos}><Save size={17}/> Cadastrar roupa</button></div><div className="form-note">O cadastro fica salvo neste navegador. As fotos são escolhidas da galeria e são compactadas para ocupar menos espaço.</div>
    </section>}
    <style>{`.gallery-upload{position:relative;display:flex;align-items:center;justify-content:center;gap:9px;min-height:58px;margin-top:10px;padding:12px 14px;border:1px dashed #555a60;border-radius:13px;background:#0d0f10;color:#fff;cursor:pointer;font-size:12px;font-weight:800;text-align:center}.gallery-upload:hover{border-color:var(--orange);background:#131517}.gallery-upload input{position:absolute!important;width:1px!important;height:1px!important;opacity:0!important;pointer-events:none}.gallery-upload svg{color:var(--orange);flex:none}.photo-preview-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-top:10px}.photo-preview{position:relative;overflow:hidden;min-width:0;height:130px;border-radius:10px;background:#0d0f10;border:1px solid #292c30}.photo-preview img{width:100%;height:100%;display:block;object-fit:cover}.photo-preview span{position:absolute;left:5px;bottom:5px;padding:3px 6px;border-radius:6px;background:rgba(0,0,0,.75);font-size:8px;color:#fff}.photo-preview button{position:absolute;right:5px;top:5px;width:25px;height:25px;border-radius:50%;display:grid;place-items:center;background:rgba(0,0,0,.78);color:#fff}.photo-preview button:hover{background:var(--orange)}.photo-count{margin-bottom:0}.admin-head>.admin-add{display:none}@media(max-width:600px){.photo-preview-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.photo-preview{height:105px}.gallery-upload{min-height:54px}}@media(max-width:380px){.photo-preview-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}`}</style>
  </main>
}

createRoot(document.getElementById('root')!).render(<App />)
